SET NAMES utf8mb4;
ALTER TABLE appeals COMMENT = '用户申诉表';
ALTER TABLE favorites COMMENT = '歌曲收藏表';
ALTER TABLE play_history COMMENT = '播放历史表';
ALTER TABLE playlist_info COMMENT = '[已废弃] 外部歌单表';
ALTER TABLE playlist_songs COMMENT = '歌单歌曲表';
ALTER TABLE recommendation_feedback COMMENT = '推荐反馈表';
ALTER TABLE recommendations COMMENT = '歌曲推荐表';
ALTER TABLE song_info COMMENT = '[已废弃] 歌曲草稿表';
ALTER TABLE songs COMMENT = '歌曲主表';
ALTER TABLE songs_update_temp COMMENT = '[已废弃] 歌曲更新表';
ALTER TABLE user_playlists COMMENT = '用户歌单表';
ALTER TABLE users COMMENT = '用户信息表';
